config/routes.rb
Rails.application.routes.draw do
  get 'number/input'
  get 'number/ajax'
  root 'number#input'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/number_controller.rb
# Class for controller
class NumberController < ApplicationController
  def input; end

  def get_binary(num)
    count = 1
    res = 0
    while num.positive? do
      res += count * (num % 2)
      count *= 10
      num = num.div(2)
    end
    res
  end

  def get_length(num)
    result = []
    while num .positive?
      result.push(num % 10)
      num = num.div(10)
    end
    result
  end

  def pal?(num)
    data = get_length(num)
    0.upto(data.length - 1) do |i|
      return false if data[i] != data[data.length - 1 - i]
    end
    true
  end

  def ajax
    @result = []
    begin
      number = Integer(params[:value])
      1.upto(number) do |num|
        pair = []
       bin_value = get_binary(num)
        pair.push(num).push(bin_value) if pal?(bin_value) && pal?(num)
       @result.push(pair) if pair.length == 2
      end
    rescue StandardError
    end
    @result.push(%w[- -]) if @result.length.zero?
    respond_to do |format|
      format.json { render json: { result: @result } }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/number_helper.rb
module NumberHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const container = document.querySelector('#number__container');

            if (!container) return;

            const form = container.querySelector('#number__form');
            const result = container.querySelector('#number__result');

            form.addEventListener('ajax:success', function(evt) {
                const response = evt.detail[0];
                console.log(response);
                let string = "<table>\n<tr><th>Десятичная система</th><th>Двоичная система</th></tr>\n";
                for (let i = 0; i < response.result.length; i++) {
                    string += "<tr>";
                    for (let j = 0; j < response.result[i].length; j++){
                        string += "<th>" + response.result[i][j] + "</th>";
                    }
                    string += "</tr>\n";
                }
                string += "</table>";
                result.innerHTML = string || 'Ответ не получен';
            });
        });
      </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/number/input.html.erb
<h1>Исходные данные</h1>
<div id="number__container">
  <%= form_with id: 'number__form', method: :get, url: number_ajax_path do |form| %>
    <%= form.number_field :value, placeholder: 'Введите натуральное число', min: 1 %>
    <%= form.submit 'Получить результат' %>
  <% end %>

  <p id="number__result"></p>
</div>